name: network_inspector_example
description: Example app for network_inspector package
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http:
  dio:
  network_inspector:
    path: ../

flutter:
  uses-material-design: true
